import time
import pandas as pd
from typing import Any
from datasets import Dataset
from ragas.run_config import RunConfig

from utils.logger import logger
from config import USE_RERANKER
from rag.models import (
    Metrics, 
    PipelineResults, 
    EvaluationComponents,)
from ragas import evaluate 
from ragas.metrics import (
    Faithfulness,
    ResponseRelevancy,
    ContextPrecision,  # Newer equivalent of ContextPrecisionWithReference
    ContextRecall
)

# -------------------------------------------------------------------------------
def get_contexts(result: PipelineResults) -> list[str]:
    """Return the document contents to use as RAGAS contexts."""

    documents = (
        result.retrieval.reranked_documents
        if USE_RERANKER
        else result.retrieval.retrieved_documents
    )

    return [document.content for document in documents]
# -------------------------------------------------------------------------------

def build_ragas_dataset(
    pipeline_results: list[PipelineResults]
)->Dataset:

    """
    Build a RAGAS-compatible Hugging Face Dataset from pipeline results.

    The function transforms the structured results produced by the RAG
    pipeline into the column format expected by RAGAS. It includes the
    original user questions, generated responses, retrieved document
    contexts, and reference answers.

    When reranking is enabled, the reranked documents are used as the
    retrieved contexts. Otherwise, the initially retrieved documents
    are used.

    Args:
        pipeline_results: Successfully processed RAG pipeline results
            containing generated answers, retrieved documents, and
            reference answers.

    Returns:
        A Hugging Face Dataset containing the data required for RAGAS
        evaluation.
    """

    # -------------------------------------------------
    # Build the evaluation dataset expected by RAGAS
    # -------------------------------------------------
    ragas_dataset = Dataset.from_dict(
        {
            "user_input": [
                result.question
                for result in pipeline_results
            ],

            "response": [
                result.answer
                for result in pipeline_results
            ],

            "retrieved_contexts": [
                get_contexts(result)
                for result in pipeline_results
            ],

            "reference": [
                result.reference
                for result in pipeline_results
            ],
        }
    )
    return ragas_dataset

#-------------------------------------------------------------------------------
def create_ragas_metrics(
    ragas_components: EvaluationComponents,
) -> list:

    """
    Create and configure the RAGAS metrics used for evaluation.

    The metrics evaluate different aspects of the RAG pipeline:
    faithfulness checks whether the generated answer is supported by
    the retrieved context, response relevancy measures how relevant
    the answer is to the user's question, and context precision and
    recall evaluate the quality of the retrieved context.

    Args:
        ragas_components: Initialized RAGAS LLM and embedding components
            used by the evaluation metrics.

    Returns:
        A list containing the configured RAGAS metric objects.
    """

    return [
        Faithfulness(
            llm=ragas_components.ragas_llm
        ),
        ResponseRelevancy(
            llm=ragas_components.ragas_llm, 
            embeddings=ragas_components.ragas_embeddings,
            strictness=1,
        ),
        ContextPrecision(
            llm=ragas_components.ragas_llm,
        ),
        ContextRecall(
            llm=ragas_components.ragas_llm,
        ),
    ] 

#-------------------------------------------------------------------------------
def run_ragas_evaluation(
    pipeline_results: list[PipelineResults], 
    ragas_components: EvaluationComponents
    )-> tuple[Any, float]:
    
    """
    Execute RAGAS evaluation on the pipeline results.

    This function:
    - Builds the RAGAS evaluation dataset.
    - Initializes the evaluation metrics.
    - Executes the RAGAS evaluation.
    - Measures the total evaluation time.

    Args:
        pipeline_results: Results generated by the RAG pipeline.
        ragas_components: Initialized RAGAS LLM and embedding components.

    Returns:
        Tuple containing:
            - RAGAS evaluation results.
            - Total evaluation time in seconds.
    """

    if not pipeline_results:
        raise RuntimeError("No successful test cases were collected.")

    logger.info("Running RAGAS evaluation.")

    # -------------------------------------------------
    # Build the evaluation dataset
    # -------------------------------------------------
    ragas_dataset = build_ragas_dataset(pipeline_results) 

    # -------------------------------------------------
    # Configure the RAGAS evaluation metrics
    # -------------------------------------------------
    metrics = create_ragas_metrics(ragas_components)

    try:

        # -------------------------------------------------
        # Execute RAGAS evaluation and measure execution time
        # -------------------------------------------------
        ragas_start = time.perf_counter()

        run_config = RunConfig(
            max_workers=1,   # serialize local Ollama calls
            timeout=180,     # allow slow CPU-based local inference to finish
            max_retries=2,   # avoid repeated expensive local retries
            max_wait=30,
        )
        ragas_results = evaluate(
            dataset=ragas_dataset,
            metrics=metrics,
            run_config=run_config,
        )
        ragas_time = round(time.perf_counter() - ragas_start, 4)

    except Exception:
        logger.exception("RAGAS evaluation failed.") 
        raise

    logger.info("RAGAS evaluation completed in %.4f seconds.", ragas_time)
    logger.info("RAGAS scores: %s", ragas_results)
 
    return ragas_results, ragas_time

#----------------------------------------------------------------------
def attach_metrics_to_pipeline_results(
    ragas_results: Any, 
    pipeline_results: list[PipelineResults]
    )-> pd.DataFrame:
    
    """
    Attach RAGAS metric scores to the corresponding pipeline results.

    The RAGAS evaluation results are first converted into a pandas
    DataFrame. The metric scores for each evaluated question are then
    mapped back to the corresponding PipelineResults object and stored
    in its metrics field.

    Args:
        ragas_results: Results returned by the RAGAS evaluation.
        pipeline_results: Pipeline results corresponding to the
            evaluated test questions.

    Returns:
        A pandas DataFrame containing the RAGAS evaluation results.
    """

    # Convert RAGAS results into a pandas DataFrame.
    df = ragas_results.to_pandas()

    nan_counts = df[["faithfulness", "answer_relevancy",
                      "context_precision", "context_recall"]].isna().sum()
    if nan_counts.sum() > 0:
        logger.warning("RAGAS metric failures (NaN) by column:\n%s", nan_counts)

    for result, (_, row) in zip(pipeline_results, df.iterrows()):
        result.metrics = Metrics(
            faithfulness=row["faithfulness"],
            answer_relevancy=row["answer_relevancy"],
            context_precision=row["context_precision"],
            context_recall=row["context_recall"],
        )
    return df