import time
import pandas as pd
from typing import Any
from datasets import Dataset

from utils.logger import logger
from config import USE_RERANKER
from rag.models import (
    Metrics, 
    PipelineResults, 
    EvaluationComponents,)
from ragas import evaluate 
from ragas.metrics import (
    Faithfulness,
    ResponseRelevancy,
    ContextPrecision,  # Newer equivalent of ContextPrecisionWithReference
    ContextRecall
)

def build_ragas_dataset(
    pipeline_results: list[PipelineResults]
)->Dataset:
    """
    Build a Hugging Face Dataset in the format required by RAGAS.

    The dataset is constructed from the outputs of the RAG pipeline,
    including the generated answers, retrieved contexts, and reference
    answers. Depending on the configuration, either the reranked
    documents or the original retrieved documents are used as contexts.

    Args:
        pipeline_results: Results produced by the RAG pipeline.

    Returns:
        Dataset formatted for RAGAS evaluation.
    """

    # -------------------------------------------------
    # Build the evaluation dataset expected by RAGAS
    # -------------------------------------------------
    ragas_dataset = Dataset.from_dict(
        {
            "user_input": [
                x.question
                for x in pipeline_results
            ],

            "response": [
                x.answer
                for x in pipeline_results
            ],

            "retrieved_contexts": [
                [
                    chunk.content
                    for chunk in (
                        x.retrieval.reranked_documents
                        if USE_RERANKER
                        else x.retrieval.retrieved_documents
                    )
                ]
                for x in pipeline_results
            ],

            "reference": [
                x.reference
                for x in pipeline_results
            ],
        }
    )
    return ragas_dataset

#-------------------------------------------------------------------------------
def create_ragas_metrics(
    ragas_components: EvaluationComponents,
) -> list:
    
    """
    Create and configure the RAGAS metrics used for evaluation.

    Args:
        ragas_components: Initialized RAGAS LLM and embedding components.

    Returns:
        List of configured RAGAS metric objects.
    """

    return [
        Faithfulness(
            llm=ragas_components.ragas_llm
        ),
        ResponseRelevancy(
            llm=ragas_components.ragas_llm, 
            embeddings=ragas_components.ragas_embeddings,
        ),
        ContextPrecision(
            llm=ragas_components.ragas_llm,
        ),
        ContextRecall(
            llm=ragas_components.ragas_llm,
        ),
    ] 

#-------------------------------------------------------------------------------
def run_ragas_evaluation(
    pipeline_results: list[PipelineResults], 
    ragas_components: EvaluationComponents
    )-> tuple[Any, float]:
    
    """
    Execute RAGAS evaluation on the pipeline results.

    This function:
    - Builds the RAGAS evaluation dataset.
    - Initializes the evaluation metrics.
    - Executes the RAGAS evaluation.
    - Measures the total evaluation time.

    Args:
        pipeline_results: Results generated by the RAG pipeline.
        ragas_components: Initialized RAGAS LLM and embedding components.

    Returns:
        Tuple containing:
            - RAGAS evaluation results.
            - Total evaluation time in seconds.
    """

    if not pipeline_results:
        raise RuntimeError("No successful test cases were collected.")

    logger.info("Running RAGAS evaluation...")

    # -------------------------------------------------
    # Build the evaluation dataset
    # -------------------------------------------------
    ragas_dataset = build_ragas_dataset(pipeline_results) 

    # -------------------------------------------------
    # Configure the RAGAS evaluation metrics
    # -------------------------------------------------
    metrics = create_ragas_metrics(ragas_components)

    try:

        # -------------------------------------------------
        # Execute RAGAS evaluation and measure execution time
        # -------------------------------------------------
        ragas_start = time.perf_counter()
        
        ragas_results = evaluate(
            dataset=ragas_dataset,
            metrics=metrics,
        )
        ragas_time = round(time.perf_counter() - ragas_start, 4)

    except Exception:
        logger.exception("RAGAS evaluation failed") 
        raise

    
    logger.info("========== RAGAS SCORES ==========")
    logger.info(ragas_results)
 
    return ragas_results, ragas_time

#----------------------------------------------------------------------
def attach_metrics_to_pipeline_results(
    ragas_results, 
    pipeline_results: list[PipelineResults]
    )-> pd.DataFrame:
    
    """
    Attach RAGAS metric scores to each pipeline result.

    The RAGAS evaluation returns a table containing metric scores for
    every evaluated question. This function maps those scores back to
    their corresponding PipelineResults objects so that all pipeline
    outputs and evaluation metrics are stored together.

    Args:
        ragas_results: Results returned by RAGAS.
        pipeline_results: Pipeline results to enrich with evaluation metrics.

    Returns:
        DataFrame containing the RAGAS evaluation scores.
    """

    # Convert RAGAS results into a pandas DataFrame.
    df = ragas_results.to_pandas()

    # Attach metric scores to each PipelineResults object.
    for result, (_, row) in zip(pipeline_results, df.iterrows()):
        result.metrics = Metrics(
            faithfulness=row["faithfulness"],
            answer_relevancy=row["answer_relevancy"],
            context_precision=row["context_precision"],
            context_recall=row["context_recall"],
        )
    
    return df