import pandas as pd
from rag.models import PipelineResults

def build_latency_summary(
    pipeline_results: list[PipelineResults], 
    num_questions: int
)-> dict:
    """
    Calculate average latency metrics across all pipeline executions.

    Args:
        pipeline_results: Results generated by the RAG pipeline.
        num_questions: Number of successfully processed questions.

    Returns:
        Dictionary containing average latency statistics.
    """

    return {
        "avg_retrieval_latency" : round(
            sum(
                r.latency.retrieval_seconds
                for r in pipeline_results
            ) / num_questions,
            4
        ),
        "avg_reranker_latency" : round(
            sum(
                r.latency.reranker_seconds
                for r in pipeline_results
            ) / num_questions,
            4
        ),
        "avg_generation_latency": round(
            sum(
                r.latency.generation_seconds
                for r in pipeline_results
            ) / num_questions,
            4
        ),
        "avg_pipeline_latency": round(
            sum(
                r.latency.pipeline_seconds
                for r in pipeline_results
            ) / num_questions,
            4
        ),
        "avg_prompt_latency": round(
            sum(
                r.latency.prompt_seconds
                for r in pipeline_results
            ) / num_questions,
            4
        )
    }

def build_token_summary(
    pipeline_results: list[PipelineResults], 
    num_questions: int
)-> dict:
    
    """
    Calculate average tokens across all pipeline executions.

    Args:
        pipeline_results: Results generated by the RAG pipeline.
        num_questions: Number of successfully processed questions.

    Returns:
        Dictionary containing average tokens statistics.
    """
    total_prompt_tokens = sum(
        r.usage.prompt_tokens
        for r in pipeline_results
    )

    total_completion_tokens = sum(
        r.usage.completion_tokens
        for r in pipeline_results
    )

    total_tokens = sum(
        r.usage.total_tokens
        for r in pipeline_results
    )

    return {
        "total_prompt_tokens": total_prompt_tokens,
        "total_completion_tokens": total_completion_tokens,
        "total_tokens": total_tokens,
        "avg_prompt_tokens": round(
            total_prompt_tokens / num_questions, 2),
        "avg_completion_tokens": round(
            total_completion_tokens/ num_questions, 2),
        "avg_total_tokens": round(
            total_tokens / num_questions, 2)
    }

def build_chunk_summary(
    pipeline_results: list[PipelineResults], 
    num_questions: int
)-> dict:
    """
    Calculate average chunks retrieved across all pipeline executions.

    Args:
        pipeline_results: Results generated by the RAG pipeline.
        num_questions: Number of successfully processed questions.

    Returns:
        Dictionary containing average chunks statistics.
    """
    return {
        "avg_chunks_retrieved": round(
            sum(
                r.retrieval_stats.retrieved
                for r in pipeline_results
            ) / num_questions,
            2
        ),
        
        "avg_chunks_after_reranker": round(
            sum(
                r.retrieval_stats.after_reranker
                for r in pipeline_results
            ) / num_questions,
            2
        )
    }

def build_ragas_summary(
    df: pd.DataFrame
) -> dict:
    """
    Calculate the average RAGAS metric scores across all evaluated questions.

    Only metrics present in the DataFrame are included in the summary,
    allowing the function to work with different RAGAS metric configurations.

    Args:
        df: DataFrame containing the RAGAS evaluation results.

    Returns:
        Dictionary containing the average score for each available RAGAS metric.
    """

    summary = {}

    # Calculate the average score for each available RAGAS metric.
    for column in [
        "faithfulness",
        "answer_relevancy",
        "response_relevancy",
        "context_precision",
        "context_recall",
    ]:
        if column in df.columns:
            summary[column] = round(df[column].mean(), 3)

    return summary

#------------------------------------------------------------------------------

def build_summary(
    test_data: list[dict], 
    pipeline_results: list[PipelineResults], 
    ragas_time: float, 
    df: pd.DataFrame, 
) -> dict:
    
    """
    Build a summary of the RAG pipeline and RAGAS evaluation results.

    The summary combines execution statistics, retrieval statistics,
    token usage, and average RAGAS metric scores into a single
    dictionary for reporting and analysis.

    Args:
        test_data: Original test dataset.
        pipeline_results: Results generated by the RAG pipeline.
        ragas_time: Total time taken to run the RAGAS evaluation.
        df: DataFrame containing the RAGAS evaluation results.

    Returns:
        Dictionary containing the experiment summary.
    """

    if not pipeline_results:
        raise RuntimeError("No successful test cases were collected.")

    num_questions = len(pipeline_results)

    # -------------------------------------------------
    # Build the overall experiment summary
    # -------------------------------------------------
    summary = {
        "total_questions": len(test_data),
        "successful_questions": num_questions,
        "failed_questions": len(test_data) - num_questions,
        "ragas_evaluation_seconds": ragas_time,
    }

    # -------------------------------------------------
    # Add pipeline execution statistics
    # -------------------------------------------------
    summary.update(build_latency_summary(pipeline_results, num_questions))
    summary.update(build_chunk_summary(pipeline_results, num_questions))
    summary.update(build_token_summary(pipeline_results, num_questions))

    # -------------------------------------------------
    # Add average RAGAS metric scores
    # -------------------------------------------------
    summary.update(build_ragas_summary(df))

    return summary